spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    jdbc-url: host=localhost user=postgres password=postgres dbname=postgres port=5432 sslmode=disable TimeZone=Asia/Shanghai
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 15
  application:
    name: randomData
    version: 1.0.0
server:
  port: 80
